version: '3.7'

services:
  db:
    container_name: MySQL
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: "renan"
      MYSQL_PASSWORD: "123456"
      MYSQL_ROOT_PASSWORD: "123456"
      MYSQL_DATABASE: "manage-labs-db"
    volumes:
      - /home/rhribeiro25/Documents/Docker/Volumes/MySql:/var/lib/mysql
    networks:
      - mysql-app-network

  app:
    container_name: ManageLabs
    image: rhribeiro25/manage-labs:1.0.3
    restart: always
    ports:
      - 9090:9090
    volumes:
      - /tmp:/var/lib/app
    networks:
      - mysql-app-network
    depends_on:
      - db

networks:
  mysql-app-network:
    driver: bridge